runtime = "text"

[[dataset]]
argument = "1000"

[[dataset]]
argument = "10000"

# NOTE(Linnea, 2021-03-31): rope implementation cannot handle > 10000
# [[dataset]]
# argument = "100000"

# [[dataset]]
# argument = "1000000"
