provides = "text"

# You can provide multiple possible commands. The first one that has all
# dependencies met is the one that will be run. In this case we use it to
# support windows.
[[command]]
required_executables = ["cat"]
command = "cat {argument}"

[[command]]
required_executables = ["type"]
command = "type {argument}"